# =============================================
# Базовые настройки SwiftLint
# =============================================
disabled_rules:
  - file_length            # Отключено для гибкости
  - function_body_length   # Контролируется через другие правила
  - type_body_length       # Контролируется через другие правила

opt_in_rules:
  - empty_count            # Ловит неоптимальные проверки на empty
  - closure_end_indentation # Форматирование замыканий
  - implicit_return        # Поощряет краткий синтаксис

# =============================================
# Стиль кода
# =============================================
# Идентификаторы
identifier_name:
  min_length: 3            # Минимум 3 символа
  max_length: 40           # Максимум 40 символов
  excluded:                # Исключения
    - id
    - to
    - x
    - y
    - dx
    - dy

type_name:
  min_length: 3
  max_length: 40
  validates_start_with_lowercase: false

# Форматирование
line_length:
  warning: 120
  error: 200
  ignores_urls: true       # Игнорировать длинные URL
  ignores_function_declarations: true
  ignores_comments: true

# Отступы
indentation_width:
  severity: warning
  indentation_width: 2     # 2 пробела для отступа

# =============================================
# Качество кода
# =============================================
force_cast: warning        # Предупреждение для force cast
force_try: warning         # Предупреждение для force try
force_unwrapping: warning  # Предупреждение для !

cyclomatic_complexity:
  warning: 10             # Сложность функций
  error: 15

# =============================================
# Безопасность
# =============================================
discouraged_direct_init:
  severity: warning
  types:                  # Нежелательные прямые инициализации
    - "Bundle"
    - "NSCalendar"
    - "NSDateFormatter"

# =============================================
# Исключения
# =============================================
excluded:
  - Pods                  # Игнорируем зависимости
  - Carthage
  - Build
  - DerivedData
  - Fastlane
  - "*.generated.swift"   # Игнорируем сгенерированные файлы

# =============================================
# Дополнительные настройки
# =============================================
trailing_whitespace:
  ignores_empty_lines: true
  ignores_comments: true

vertical_whitespace:
  max_empty_lines: 2       # Макс. 2 пустых строки подряд

redundant_type_annotation: warning

# =============================================
# SwiftUI специфика
# =============================================
private_over_fileprivate: warning # Предпочитать private

# =============================================
# Автоисправление (при запуске с --fix)
# =============================================
# Правила, которые можно автоматически исправить:
auto_correct: true
